---
- name: Gather facts
  hosts: all
  gather_facts: true
  any_errors_fatal: true
  become: true
  tasks:
    - set_fact:
        playbook_action: install
  tags:
    - always

- name: Installing Nomad
  hosts: nomad
  become: true
  gather_facts: false
  roles:
      - nomad
  vars:
    nomad_version: 1.3.4
    nomad_acl_enabled: true
    nomad_use_consul: true
    nomad_bind_address: "0.0.0.0"
    nomad_reserved:
      cpu: 100
      memory: 1000
      disk: 0
      ports: "22"
    nomad_config_custom:
      log_rotate_bytes: 20000000
      log_rotate_max_files: 5
    nomad_host_volumes_enable: true
    nomad_retry_join: true
    nomad_plugins:
      docker:
        config:
          gc:
            image: false
          auth:
            config: "/root/.docker/config.json"
          volumes:
            enabled: true
          infra_image_pull_timeout: "1h"
          pull_activity_timeout: "1h"
  tags:
    - nomad